version: '3'

services:

  spring-security-db:
    image: postgres:12-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "eazybank"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    ports:
      - "8089:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
