version: '3'

services:

  spring-security-db:
    image: postgres:12-alpine
    container_name: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "eazybank"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start-dev
    ports:
      - "8089:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
      #      It basically runs it with SSL disabled, allowing you to create HTTP connections with it
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    networks:
      - elastic

  logstash:
    image: logstash:8.12.1
    container_name: logstash
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "9600:9600"
      - "5000:5000/tcp"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  kibana:
    image: kibana:8.12.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge