version: '3'

services:

  spring-security-db:
    image: postgres:12-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "eazybank"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
